import { create } from "zustand";
import { GameMode, type Locomotion } from "./types";
import type { SymbolicArchetype, SymbolicEvent } from "./symbolicBus";
import { generateRoom, seedForExit, type Room } from "./roomApi";

// Rooms are deterministic by seed, so a session cache makes re-crossing a door
// you already opened instant and free — no second LLM call. Kept at module scope
// (not in the store) so reads never trigger React re-renders.
const roomCache = new Map<number, Room>();

// Central runtime state, the React/Three.js analogue of LabyrinthManager.
// EnterConsoleMode / ExitConsoleMode drive the same Exploration <-> Console
// flow as the Unity coordinator, including the brief Transition state.
interface GameState {
  mode: GameMode;
  activeConsoleId: string | null;
  /** id of the console the player is currently close enough to interact with */
  nearbyConsoleId: string | null;
  /** id of the ritual glyph the player is currently close enough to invoke */
  nearbyGlyphId: string | null;
  /** index of the room door the player is currently close enough to cross */
  nearbyExit: number | null;
  /** current locomotion clip, mirrored from the Player for the debug HUD */
  locomotion: Locomotion;
  /** most recent symbolic event, surfaced in the debug HUD */
  lastSymbol: SymbolicEvent | null;
  /** room generated by the LLM server on the last glyph invocation / door */
  room: Room | null;
  /** archetype of the active backrooms descent — reused when crossing doors */
  roomArchetype: SymbolicArchetype | null;
  roomLoading: boolean;
  roomError: string | null;
  /** how many rooms have been rewritten this session — feeds generation depth */
  depth: number;

  enterConsoleMode: (consoleId: string) => void;
  exitConsoleMode: () => void;
  setNearbyConsole: (consoleId: string | null) => void;
  setNearbyGlyph: (glyphId: string | null) => void;
  setNearbyExit: (index: number | null) => void;
  setLocomotion: (locomotion: Locomotion) => void;
  setLastSymbol: (event: SymbolicEvent) => void;
  /** glyph pressed in the world — opens the first room of a descent */
  invokeGlyph: (archetype: SymbolicArchetype, glyphId: string) => void;
  /** cross exit[index] of the current room — load/generate the next one */
  takeExit: (index: number) => void;
  dismissRoom: () => void;
}

const TRANSITION_MS = 500; // matches _modeTransitionDuration

export const useGame = create<GameState>((set, get) => {
  // Single source of truth for loading a room by seed: cache hit -> instant and
  // free; miss -> generate via the LLM server and cache the result. Shared by
  // the glyph-invoke entry point and every door crossing.
  const loadRoom = (
    seed: number,
    archetype: SymbolicArchetype,
    fragments: string[]
  ) => {
    const cached = roomCache.get(seed);
    if (cached) {
      set({ room: cached, roomArchetype: archetype, roomLoading: false, roomError: null, mode: GameMode.Room });
      return;
    }
    set({ roomLoading: true, roomError: null, roomArchetype: archetype });
    generateRoom({ seed, archetype, depth: get().depth, fragments })
      .then((room) => {
        roomCache.set(seed, room);
        set((s) => ({ room, roomLoading: false, roomError: null, depth: s.depth + 1, mode: GameMode.Room }));
      })
      .catch((e) => set({ roomLoading: false, roomError: String(e) }));
  };

  return {
  mode: GameMode.Exploration,
  activeConsoleId: null,
  nearbyConsoleId: null,
  nearbyGlyphId: null,
  nearbyExit: null,
  locomotion: "idle",
  lastSymbol: null,
  room: null,
  roomArchetype: null,
  roomLoading: false,
  roomError: null,
  depth: 0,

  enterConsoleMode: (consoleId) => {
    if (get().mode !== GameMode.Exploration) return;
    set({ mode: GameMode.Transition, activeConsoleId: consoleId });
    window.setTimeout(() => {
      // Only settle into Console if we are still transitioning into it.
      if (get().activeConsoleId === consoleId) {
        set({ mode: GameMode.Console });
      }
    }, TRANSITION_MS);
  },

  exitConsoleMode: () => {
    if (get().mode !== GameMode.Console) return;
    set({ mode: GameMode.Transition, activeConsoleId: null });
    window.setTimeout(() => {
      if (get().activeConsoleId === null) {
        set({ mode: GameMode.Exploration });
      }
    }, TRANSITION_MS);
  },

  setNearbyConsole: (consoleId) => set({ nearbyConsoleId: consoleId }),

  setNearbyGlyph: (glyphId) => set({ nearbyGlyphId: glyphId }),

  setNearbyExit: (index) => set({ nearbyExit: index }),

  setLocomotion: (locomotion) => set({ locomotion }),

  setLastSymbol: (lastSymbol) => set({ lastSymbol }),

  invokeGlyph: (archetype, glyphId) => {
    if (get().roomLoading) return;
    const seed = seedForExit((get().depth + 1) * 0x9e3779b1, glyphId.length + archetype.length);
    loadRoom(seed, archetype, []);
  },

  takeExit: (index) => {
    const { room, roomArchetype, roomLoading } = get();
    if (!room || roomLoading || !roomArchetype) return;
    if (index < 0 || index >= room.exits.length) return;
    loadRoom(seedForExit(room.seed, index), roomArchetype, [room.inscription]);
  },

  dismissRoom: () =>
    set((s) => ({
      room: null,
      roomError: null,
      roomArchetype: null,
      nearbyExit: null,
      mode: s.mode === GameMode.Room ? GameMode.Exploration : s.mode,
    })),
  };
});

// Dev-only handle for debugging the mode flow from the console / tests.
if (import.meta.env.DEV) {
  (window as unknown as { __game: typeof useGame }).__game = useGame;
}
