import { create } from "zustand";
import { GameMode, type Locomotion } from "./types";
import type { SymbolicArchetype, SymbolicEvent } from "./symbolicBus";
import { generateRoom, seedForExit, type Room } from "./roomApi";

// Rooms are deterministic by seed, so a session cache makes re-crossing a door
// you already opened instant and free — no second LLM call. Kept at module scope
// (not in the store) so reads never trigger React re-renders.
const roomCache = new Map<number, Room>();

const HISTORY_LIMIT = 8;
const FAKE_PENALTY = 45; // stability lost to a false door

// One door per room is a trap, chosen deterministically from the seed so the
// same room always lies the same way. Rooms with a single exit are never traps
// (that would be an inescapable dead end).
export function fakeExitForRoom(room: Room): number {
  return room.exits.length > 1 ? room.seed % room.exits.length : -1;
}

// Where the player stood in the maze when they entered a room, so leaving a room
// drops them back exactly where they were instead of the maze centre.
export interface MazePose {
  pos: [number, number, number];
  yaw: number;
}

// Central runtime state, the React/Three.js analogue of LabyrinthManager.
// EnterConsoleMode / ExitConsoleMode drive the same Exploration <-> Console
// flow as the Unity coordinator, including the brief Transition state.
interface GameState {
  mode: GameMode;
  activeConsoleId: string | null;
  /** id of the console the player is currently close enough to interact with */
  nearbyConsoleId: string | null;
  /** id of the ritual glyph the player is currently close enough to invoke */
  nearbyGlyphId: string | null;
  /** index of the room door the player is currently close enough to cross */
  nearbyExit: number | null;
  /** current locomotion clip, mirrored from the Player for the debug HUD */
  locomotion: Locomotion;
  /** most recent symbolic event, surfaced in the debug HUD */
  lastSymbol: SymbolicEvent | null;
  /** room generated by the LLM server on the last glyph invocation / door */
  room: Room | null;
  /** archetype of the active backrooms descent — reused when crossing doors */
  roomArchetype: SymbolicArchetype | null;
  roomLoading: boolean;
  roomError: string | null;
  /** how many rooms have been rewritten this session — feeds generation depth */
  depth: number;
  /** seed of the room the current one was entered from (null at a descent root) */
  parentSeed: number | null;
  /** rooms visited this descent, oldest first — drives the breadcrumb HUD */
  roomHistory: Room[];
  /** player's maze stance, captured on entering a room and restored on leaving */
  mazePose: MazePose | null;
  /** room integrity 0-100: decays with time + dread, collapse at 0 */
  stability: number;
  /** seeds of rooms that have proven to bite (false door / collapse) */
  dangerousSeeds: number[];

  enterConsoleMode: (consoleId: string) => void;
  exitConsoleMode: () => void;
  setNearbyConsole: (consoleId: string | null) => void;
  setNearbyGlyph: (glyphId: string | null) => void;
  setNearbyExit: (index: number | null) => void;
  setLocomotion: (locomotion: Locomotion) => void;
  setLastSymbol: (event: SymbolicEvent) => void;
  setMazePose: (pose: MazePose) => void;
  setStability: (value: number) => void;
  /** glyph pressed in the world — opens the first room of a descent */
  invokeGlyph: (archetype: SymbolicArchetype, glyphId: string) => void;
  /** cross exit[index] of the current room — load/generate the next one */
  takeExit: (index: number) => void;
  /** stability hit 0 — mark the room dangerous and expel to the maze */
  collapseRoom: () => void;
  dismissRoom: () => void;
}

const TRANSITION_MS = 500; // matches _modeTransitionDuration

export const useGame = create<GameState>((set, get) => {
  // Single source of truth for loading a room by seed: cache hit -> instant and
  // free; miss -> generate via the LLM server and cache the result. Shared by
  // the glyph-invoke entry point and every door crossing.
  const pushHistory = (history: Room[], room: Room): Room[] => {
    const next = [...history.filter((r) => r.seed !== room.seed), room];
    return next.slice(-HISTORY_LIMIT);
  };

  const loadRoom = (
    seed: number,
    archetype: SymbolicArchetype,
    fragments: string[],
    parentSeed: number | null
  ) => {
    const cached = roomCache.get(seed);
    if (cached) {
      set((s) => ({
        room: cached,
        roomArchetype: archetype,
        roomLoading: false,
        roomError: null,
        mode: GameMode.Room,
        parentSeed,
        roomHistory: pushHistory(s.roomHistory, cached),
        stability: 100,
      }));
      return;
    }
    set({ roomLoading: true, roomError: null, roomArchetype: archetype });
    generateRoom({ seed, archetype, depth: get().depth, fragments })
      .then((room) => {
        roomCache.set(seed, room);
        set((s) => ({
          room,
          roomLoading: false,
          roomError: null,
          depth: s.depth + 1,
          mode: GameMode.Room,
          parentSeed,
          roomHistory: pushHistory(s.roomHistory, room),
          stability: 100,
        }));
      })
      .catch((e) => set({ roomLoading: false, roomError: String(e) }));
  };

  return {
  mode: GameMode.Exploration,
  activeConsoleId: null,
  nearbyConsoleId: null,
  nearbyGlyphId: null,
  nearbyExit: null,
  locomotion: "idle",
  lastSymbol: null,
  room: null,
  roomArchetype: null,
  roomLoading: false,
  roomError: null,
  depth: 0,
  parentSeed: null,
  roomHistory: [],
  mazePose: null,
  stability: 100,
  dangerousSeeds: [],

  enterConsoleMode: (consoleId) => {
    if (get().mode !== GameMode.Exploration) return;
    set({ mode: GameMode.Transition, activeConsoleId: consoleId });
    window.setTimeout(() => {
      // Only settle into Console if we are still transitioning into it.
      if (get().activeConsoleId === consoleId) {
        set({ mode: GameMode.Console });
      }
    }, TRANSITION_MS);
  },

  exitConsoleMode: () => {
    if (get().mode !== GameMode.Console) return;
    set({ mode: GameMode.Transition, activeConsoleId: null });
    window.setTimeout(() => {
      if (get().activeConsoleId === null) {
        set({ mode: GameMode.Exploration });
      }
    }, TRANSITION_MS);
  },

  setNearbyConsole: (consoleId) => set({ nearbyConsoleId: consoleId }),

  setNearbyGlyph: (glyphId) => set({ nearbyGlyphId: glyphId }),

  setNearbyExit: (index) => set({ nearbyExit: index }),

  setLocomotion: (locomotion) => set({ locomotion }),

  setLastSymbol: (lastSymbol) => set({ lastSymbol }),

  setMazePose: (mazePose) => set({ mazePose }),

  setStability: (value) => set({ stability: Math.max(0, Math.min(100, value)) }),

  invokeGlyph: (archetype, glyphId) => {
    if (get().roomLoading) return;
    const seed = seedForExit((get().depth + 1) * 0x9e3779b1, glyphId.length + archetype.length);
    // a glyph opens a fresh descent — clear the previous breadcrumb trail
    set({ roomHistory: [] });
    loadRoom(seed, archetype, [], null);
  },

  takeExit: (index) => {
    const { room, roomArchetype, roomLoading } = get();
    if (!room || roomLoading || !roomArchetype) return;
    if (index < 0 || index >= room.exits.length) return;
    // a false door bites: it costs stability and brands the room, it never leads on
    if (index === fakeExitForRoom(room)) {
      set((s) => ({
        stability: Math.max(0, s.stability - FAKE_PENALTY),
        dangerousSeeds: s.dangerousSeeds.includes(room.seed)
          ? s.dangerousSeeds
          : [...s.dangerousSeeds, room.seed],
      }));
      if (get().stability <= 0) get().collapseRoom();
      return;
    }
    loadRoom(seedForExit(room.seed, index), roomArchetype, [room.inscription], room.seed);
  },

  collapseRoom: () =>
    set((s) => ({
      room: null,
      roomError: null,
      roomArchetype: null,
      nearbyExit: null,
      parentSeed: null,
      roomHistory: [],
      stability: 100,
      dangerousSeeds:
        s.room && !s.dangerousSeeds.includes(s.room.seed)
          ? [...s.dangerousSeeds, s.room.seed]
          : s.dangerousSeeds,
      mode: s.mode === GameMode.Room ? GameMode.Exploration : s.mode,
    })),

  dismissRoom: () =>
    set((s) => ({
      room: null,
      roomError: null,
      roomArchetype: null,
      nearbyExit: null,
      parentSeed: null,
      roomHistory: [],
      stability: 100,
      mode: s.mode === GameMode.Room ? GameMode.Exploration : s.mode,
    })),
  };
});

// Dev-only handle for debugging the mode flow from the console / tests.
if (import.meta.env.DEV) {
  (window as unknown as { __game: typeof useGame }).__game = useGame;
}
